### ISSUE TITLE
关于使用上的问题

### ISSUE THREAD

**Issue by Prevalence** [zc8424/QuantTester#1]
你好，能简单提一下这个工程怎么运行吗？

**Comment by zc8424** [comment]
你好, 这个项目是我业余写的, 目前严重缺乏文档, 非常抱歉.
我可以在这里先简单说两句, 回头一定认真把文档补上.

写这个程序主要是受了MetaTrader的启发, 其策略回测功能写的非常棒, 很容易使用, 显示结果也很直观.
而国内的多数免费的期货交易软件的回测功能都太过简陋, 所以自己写了一个, 参考了MetaTrader的诸多功能.

今天先说说数据来源
目前支持两种数据来源: 飞狐交易师和一款名叫"心忆复盘软件"的免费程序提供的免费数据
其数据导入功能分别在data,foxtrade和data.sinyee两个包内实现
其中飞狐交易师的数据需要预先使用ExportData插件(dll)导出到文件, 这个ExportData我也开源了
而"心忆复盘软件"的数据在http://www.sinyee.net/download.htm可以下载到
这两个数据来源算是网上找得到的相对比较靠谱的免费数据.
当然我对数据格式等都作了抽象, 今后如果有质量更高的数据源或者自己从实盘搜集的数据也可以加进来.

**Comment by zc8424** [comment]
数据格式可以分为两类: K线(Bar) 和 单笔成交(Tick), 相关的类在data.struct包里.
另外, FutureBar(期货K线)继承了Bar, 增加了持仓量(openInterest), 合约月份(contractMonth), 结算价(settlement) 三个字段, 这三个字段是期货特有的, 股票和ETF没有这些数据。
还有, DetailedTick(带一档买卖盘口的单笔成交数据)继承了Tick, 增加了卖一价(sellPrice), 卖一量(sellVolume), 买一价(buyPrice), 买一量(buyVolume)和成交方向(direction)五个字段.
BarSeries和FutureBarSeries分别是Bar和FutureBar的数组版本, 可以表示一段连续时间的K线数据, 方便计算各类指标.

**Comment by zc8424** [comment]
项目里的config.ini文件是用来配置数据来源的存放目录的.
比如我的电脑上面是这样配置的:
KTExportDir=F:\\KT\\KTExportData\\
SinYeeDataDir=D:\\SinYeeData\\
其中F:\\KT\\是飞狐交易师的安装路径, KTExportData目录是ExportData程序自动创建的, 里面存放的就是从飞狐交易师导出的各个期货合约(也可以是股票, ETF)的各种时段的K线数据.
D:\\SinYeeData\\目录里存放的是心忆软件的网盘里所有的压缩文件解压后的内容放在一起.

今天先说到这...

**Comment by zc8424** [comment]
昨天匆忙写了一点, 对你可能不是很有用.
但是有关策略回测牵扯到了太多头绪, 确实很难做到能够方便上手使用.
下面我会贴一些实际运行的效果出来, 看看是否和你所想象的以及所需要的一样.
如果一样的话, 我很乐意与你分享更多的细节并一同继续开发、完善这个程序.
如果不是的话, 那也许你应该关闭这个话题, 去别的开源项目逛逛.
不管怎么样, 对我而言这都是一个好的开始, 这个话题中的内容我会整理放到Wiki, 并在Wiki里进一步完善相关文档.

**Comment by zc8424** [comment]
这是一张沪深300指数的移动平均线图, 移动平均线类型为普通型(MODE_SMA), 周期是40天.
图中红线表示阳线, 绿线表示阴线, 粉红色的点组成的线就是移动平均线.
图片是程序自动生成的, 图片的高度、宽度等设置都可以由参数调节.
除了移动平均线之外, 程序还内置了RSI, MACD, CCI等常用指标, 可以方便得将这些指标绘制成图形.
另外, MetaTrader软件内置的那些用Mql5语言编写的指标可以很方便得移植过来.
这项指标绘图功能只是用于检查指标的编写是否正确, 所以实现的比较粗糙.
![sma](https://cloud.githubusercontent.com/assets/23719666/23506048/2e6c5f4c-ff81-11e6-8cce-6ed5d7136242.png)

**Comment by zc8424** [comment]
接下来是一个简单的通道突破策略的回测结果.
测试合约是白银主力连续合约, 回测模式是简单模式(SimpleStrategyTester, 有关回测模式详见WiKi),
测试时间为2012年5月10日到2017年1月1日, 通道天数为36天.
![channelbreakstrategy](https://cloud.githubusercontent.com/assets/23719666/23506889/6cc36c5a-ff85-11e6-9f1c-180fa732af1d.png)
ProfitDays:	526
LossDays:	562
Total_Days:	1133
ProfitRatio:	0.023031313
MaxDrawDown:	26506.625
SharpeRatio:	-0.827383
GrossProfit:	259389.5
GrossLoss:	236358.19
ProfitFactor:	1.0974424
TotalTrades:	14
LongTrades:	7
ShortTrades:	7

**Comment by zc8424** [comment]
然后是策略参数优化功能, 还以通道突破策略为例.
同样采用白银主力连续合约, 简单回测模式, 样本时间为2012年5月10日到2017年1月1日.
测试参数为通道天数, 参数范围选择4~200, 步进2.
优化结果按照ProfitRatio从小到大排序, 如下:
76,	ProfitRatio: -0.015487875	MaxDrawDown: 48570.375
78,	ProfitRatio: -0.015297812	MaxDrawDown: 48570.375
74,	ProfitRatio: -0.012977063	MaxDrawDown: 48570.375
30,	ProfitRatio: -0.0049191876	MaxDrawDown: 32760.625
72,	ProfitRatio: -0.0027679375	MaxDrawDown: 40732.0
70,	ProfitRatio: -4.70625E-5	MaxDrawDown: 38851.375
24,	ProfitRatio: 9.4E-5	MaxDrawDown: 28461.875
18,	ProfitRatio: 5.69875E-4	MaxDrawDown: 26837.125
28,	ProfitRatio: 0.0025808124	MaxDrawDown: 29441.625
64,	ProfitRatio: 0.003856125	MaxDrawDown: 36688.25
62,	ProfitRatio: 0.0049758125	MaxDrawDown: 35788.625
58,	ProfitRatio: 0.0049858126	MaxDrawDown: 35788.625
68,	ProfitRatio: 0.005004625	MaxDrawDown: 35809.875
56,	ProfitRatio: 0.0054059373	MaxDrawDown: 35788.625
66,	ProfitRatio: 0.0057140626	MaxDrawDown: 34670.25
60,	ProfitRatio: 0.005976125	MaxDrawDown: 35788.625
22,	ProfitRatio: 0.0071346876	MaxDrawDown: 21381.125
26,	ProfitRatio: 0.0071595	MaxDrawDown: 28461.875
8,	ProfitRatio: 0.00732325	MaxDrawDown: 23589.75
48,	ProfitRatio: 0.008336875	MaxDrawDown: 33447.875
54,	ProfitRatio: 0.008577	MaxDrawDown: 33447.875
50,	ProfitRatio: 0.008597	MaxDrawDown: 33447.875
32,	ProfitRatio: 0.008734438	MaxDrawDown: 33660.375
52,	ProfitRatio: 0.009017125	MaxDrawDown: 33447.875
20,	ProfitRatio: 0.009836188	MaxDrawDown: 24027.375
10,	ProfitRatio: 0.011708938	MaxDrawDown: 26435.5
16,	ProfitRatio: 0.01173175	MaxDrawDown: 22077.25
6,	ProfitRatio: 0.011926625	MaxDrawDown: 27435.625
42,	ProfitRatio: 0.013866375	MaxDrawDown: 31777.25
44,	ProfitRatio: 0.0142565	MaxDrawDown: 31777.25
12,	ProfitRatio: 0.015197688	MaxDrawDown: 22056.125
34,	ProfitRatio: 0.016184438	MaxDrawDown: 32633.125
38,	ProfitRatio: 0.016230062	MaxDrawDown: 26506.625
14,	ProfitRatio: 0.016281813	MaxDrawDown: 19217.75
80,	ProfitRatio: 0.017483626	MaxDrawDown: 16693.0
40,	ProfitRatio: 0.018027375	MaxDrawDown: 27606.25
46,	ProfitRatio: 0.019367	MaxDrawDown: 26306.625
36,	ProfitRatio: 0.020161312	MaxDrawDown: 26506.625
4,	ProfitRatio: 0.030483687	MaxDrawDown: 12499.0

**Comment by zc8424** [comment]
目前实现的主要功能就这么多, 其实通过自己编写一些指标和策略已经可以做很多事情了.
值得一提的是, 策略参数优化功能支持多线程, 可以根据你的CPU选择合适的线程数.

整个项目使用Java语言编写, 并使用了很多Java8的新特性.
虽然Java语言在执行速度上不及C++等传统编译型语言, 但是其在跨平台、多线程等方面较有优势.
而且程序里还用到了Java的反射(reflect), 这是C++所不具备的.

今天先说这些, 不知道对你有没有什么帮助?

**Comment by Prevalence** [comment]
非常感谢您如此详细的解释，我觉得我要在这上面花点功夫才能好好理解，我先关闭这个话题吧，如果在琢磨过程中有实在解决不了的问题的话我会在问您的。
